---

name: ci

on: [push]

jobs:
  test:
    name: test (${{ matrix.ruby.name }}, ${{ matrix.deps }})
    runs-on: ${{ matrix.os }}

    timeout-minutes: 15

    strategy:
      fail-fast: false

      matrix:
        ruby: [{ name: 3.1, value: 3.1.2 }, { name: 2.7, value: 2.7.2 }]

        os: [ubuntu-22.04]

        deps: [rails_70, rails_70_hotwire, rails_61, rails_61_turbolinks]

    env:
      COVERAGE: false
      SUPPRESS_JASMINE_DEPRECATION: true

    steps:
      - uses: actions/checkout@v2

      - name: Configure bundler
        run: |
          echo "BUNDLE_GEMFILE=gemfiles/${{ matrix.deps }}.gemfile" >> $GITHUB_ENV
          echo "BUNDLE_PATH=$(pwd)/gemfiles/${{ matrix.deps }}/vendor/bundle" >> $GITHUB_ENV

      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby.value }}
          bundler-cache: true

      - name: Run tests
        run: bundle exec rake
